import { StyleSheet } from "react-native";





export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0F1115", paddingHorizontal: 25 },
  header: {
    marginTop: 10,
    marginBottom: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  welcome: { fontSize: 24, fontWeight: "800", color: "#FFF" },
  date: { fontSize: 14, color: "#94A3B8", marginTop: 4, fontWeight: "600" },
  profileBadge: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: "#1C1F26",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#2D333F",
  },
  profileChar: { color: "#00F5D4", fontWeight: "bold", fontSize: 18 },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },
  exploreBtn: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: "#00F5D4",
    paddingVertical: 22,
    paddingHorizontal: 35,
    borderRadius: 25,
    shadowColor: "#00F5D4",
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 8,
  },
  btnText: { color: "#0F1115", fontWeight: "800", fontSize: 18 },
  discoveryWrapper: { flex: 1, paddingBottom: 20 },
  navigation: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  navIcon: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  counter: { color: "#94A3B8", fontWeight: "700", fontSize: 14 },
  card: {
    backgroundColor: "#1C1F26",
    borderRadius: 35,
    padding: 30,
    flex: 0,
    maxHeight: 600,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#2D333F",
    justifyContent: "center",
  },
  sourceTag: {
    color: "#00F5D4",
    fontWeight: "800",
    fontSize: 12,
    textTransform: "uppercase",
    marginBottom: 15,
    letterSpacing: 1.5,
  },
  cardTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: "#FFF",
    lineHeight: 40,
    marginBottom: 20,
    flexShrink: 1,
  },
  cardExcerpt: {
    fontSize: 17,
    color: "#94A3B8",
    lineHeight: 28,
    marginBottom: 35,
    flexShrink: 1,
  },
  readMoreBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 40,
  },
  readMoreText: { color: "#00F5D4", fontSize: 18, fontWeight: "700" },
  actions: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: "#2D333F",
    paddingTop: 30,
  },
  actionBtn: {
    width: 55,
    height: 55,
    borderRadius: 28,
    backgroundColor: "#2D333F",
    justifyContent: "center",
    alignItems: "center",
  },
});
